### ISSUE TITLE
Artwork download stalling

### ISSUE THREAD

**Issue by ejuarezg** [irahorecka/youtube2audio#10]
If the artwork download stalls, then the code adding the metadata is not executed. I suspect this has to do with the `requests.get` function in the `set_mp3_metadata` function. However, I could not find a solution, even after using the `timeout` option. This issue is not logged by the program and the MP3 file gets transcoded fine, just without the metadata.

**Comment by irahorecka** [comment]
An interesting find - thanks for reporting. So let me reiterate this to make sure I understand what's happening:
- When you click Ask butler, the application stalls in the artwork. This function is delegated to a new thread, so it should not freeze the application, thus allowing you to download the unannotated MP3. 

I agree that it is a requests.get freeze. The reason it is not throwing an exception is because it is handled in the threadpool, which has very poor traceback features. Timeout is a good suggestion, btw. The sudden halt to this feature is probably a deadlock in the executing threads.

**Comment by ejuarezg** [comment]
I managed to figure out the root of the problem and it does not have to do with Ask butler. It is an issue with `requests.get` in `set_mp3_metadata` function throwing an `requests.exceptions.MissingSchema` that is not caught. This exception is triggered by trying to request from an invalid URL.

I added code to catch the exception which basically skips adding artwork if the exception occurs. I also added timeout values for the request in case the problem actually is a stalled artwork download.

In essence, the problem had less to do with artwork download stalling and more to do with an uncaught exception that made it so the rest of the metadata code was never reached.

**Comment by irahorecka** [comment]
@ejuarezg this is great - could you submit a separate PR for the artwork stall? I decided that for this version of the GUI I would like to keep the solely MP3 format. In the next version, I would like to work with you again for the MP4 converter. 

Thanks for your help!

[EDIT] on a second thought, please hold on just a second - i just pulled your PR to look at the app and I like what you did...

**Comment by irahorecka** [comment]
merged PR
